### PR TITLE
Fix test cases for send, run and imposterParser

### LINKED ISSUE #360: Test: update send & run parser test for new url validation

### PR DESCRIPTION
**Pull request by tlylt**
Fixes #360

### CODE REVIEW

File: src/main/java/seedu/us/among/model/endpoint/Address.java [hunk 1]
```diff
@@ -19,8 +21,10 @@
     /*
      * The first character of the address must not be a whitespace,
      * otherwise " " (a blank string) becomes a valid input.
+     * Adapted from https://stackoverflow.com/a/163398/13725861
      */
-    public static final String VALIDATION_REGEX = "[^\\s].*";
+    public static final Pattern VALIDATION_REGEX =
+            Pattern.compile("^(https?|ftp|file)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]");
```
Comment (tjtanjin) [inline src/main/java/seedu/us/among/model/endpoint/Address.java:27]: I think the match for `ftp` and `file` are not necessary since they are not protocols we support.

**Review by tjtanjin — APPROVED** [review]
LGTM! :) Can consider tweaking the validation regex.

File: src/main/java/seedu/us/among/model/endpoint/Address.java (hunk 1 above)
Comment (tlylt) [reply src/main/java/seedu/us/among/model/endpoint/Address.java:27]: Alright will remove the two
