### PR TITLE
Bug: Fix test cases

### LINKED ISSUE #126: Bug: Help fix some fix test cases

### PR DESCRIPTION
**Pull request by JulietTeoh**
I helped to fix some test cases that were removed from the code previously. 

Important to note: in our current code, only endpoints with the same method AND address AND tags will be seen as equal and throw an error.

I also added docs/TestsToFix.txt, which states the remaining files which have test cases to be fixed, such that future test fixers/bug fixers will have an easier time locating the files.

Resolves #126

### CODE REVIEW

File: src/main/java/seedu/us/among/model/endpoint/Endpoint.java [hunk 1]
```diff
@@ -75,8 +75,18 @@ public boolean isSameEndpoint(Endpoint otherEndpoint) {
...
+        if (otherEndpoint == null) {
+            return false;
+        } else {
+            if (otherEndpoint.getMethod().equals(getMethod()) && otherEndpoint.getAddress().equals(getAddress())
+                    && otherEndpoint.getTags().equals(getTags())) {
+                return true;
+            } else {
+                return false;
+            }
+        }
```
Comment (ong6) [inline src/main/java/seedu/us/among/model/endpoint/Endpoint.java:89]: You can actually use the Equals method in this same class since the equals method checks for if method, address and tags are the same.

File: src/main/java/seedu/us/among/model/endpoint/UniqueEndpointList.java [hunk 2]
```diff
@@ -124,7 +124,7 @@ public int hashCode() {
     /**
      * Returns true if {@code endpoints} contains only unique endpoints.
      */
-    private boolean personsAreUnique(List<Endpoint> endpoints) {
+    private boolean endpointsAreUnique(List<Endpoint> endpoints) {
         for (int i = 0; i < endpoints.size() - 1; i++) {
             for (int j = i + 1; j < endpoints.size(); j++) {
                 if (endpoints.get(i).isSameEndpoint(endpoints.get(j))) {
```
Comment (ong6) [inline src/main/java/seedu/us/among/model/endpoint/UniqueEndpointList.java:130]: nice catch on the naming here

File: src/test/java/seedu/us/among/logic/commands/EditCommandTest.java [hunk 3]
```diff
@@ -48,25 +48,25 @@ public void execute_allFieldsSpecifiedUnfilteredList_success() {
...
 
-    //     Model expectedModel = new ModelManager(new EndpointList(model.getEndpointList()), new UserPrefs());
-    //     expectedModel.setEndpoint(lastEndpoint, editedEndpoint);
+        Model expectedModel = new ModelManager(new EndpointList(model.getEndpointList()), new UserPrefs());
+        expectedModel.setEndpoint(lastEndpoint, editedEndpoint);
 
-    //     assertCommandSuccess(editCommand, model, expectedMessage, expectedModel); //to-do
-    // }
+        assertCommandSuccess(editCommand, model, expectedMessage, expectedModel);
+    }
```
Comment (ong6) [inline src/test/java/seedu/us/among/logic/commands/EditCommandTest.java:69]: Since we are not done with EditCommand yet, perhaps we should keep this as a to-do since when we change EditCommand it may lead to some more errors here.

**Review by ong6 — APPROVED** [review]
Overall LGTM, I will approve the merging first, but do take a look at some of my comments. I think it's ok if you don't change anything also.

File: src/test/java/seedu/us/among/logic/commands/EditCommandTest.java (hunk 3 above)
Comment (tjtanjin) [reply src/test/java/seedu/us/among/logic/commands/EditCommandTest.java:69]: I think there's a good chance more tests will be breaking given how the `header` and `data` attributes have not been implemented yet. At the same time, I am also hesitant about commenting out all the test cases.

The consideration I have is that making several small fixes to pass them might be easier compared to having to make a single big change to all test cases at the same time. Depending on the implementation for `header` and `data`, ensuring the test cases pass now may prevent further complications down the road. Just a thought :D

**Review by tjtanjin — APPROVED** [review]
I think this looks good too!
