### PR TITLE
Fix: add headers to get request and trim headers properly

### LINKED ISSUE #180: Fix: missing headers in get request and values not correctly parsed
Header values contain leading and trailing brackets and quotations.
Get request unable to set headers.

### PR DESCRIPTION
**Pull request by tjtanjin**
Remove leading/trailing brackets and quotations from headers (to be updated again once parsing is updated on add command).
Add setting of headers to get request.

Fixes #180

### CODE REVIEW

File: src/main/java/seedu/us/among/commons/util/HeaderUtil.java [hunk 1]
```diff
@@ -20,9 +20,12 @@
         HashMap<String, String> headerMap = new HashMap<>();
         for (Header header : headerSet) {
             String headerString = header.toString();
+            //to-do update trimming once handling of headers is updated on add
+            //trim leading and trailing brackets and quotations
+            headerString = headerString.substring(2, headerString.length() - 2);
```
Comment (JulietTeoh) [inline src/main/java/seedu/us/among/commons/util/HeaderUtil.java:25]: Just to confirm, Header's regex checks that a header is in the JSON format right? 

If not, such deletion before checking may lead to bugs.

**Review by JulietTeoh — APPROVED** [review]
Everything looks ok!

File: src/main/java/seedu/us/among/commons/util/HeaderUtil.java (hunk 1 above)
Comment (tjtanjin) [reply src/main/java/seedu/us/among/commons/util/HeaderUtil.java:25]: There's no check for header to be in json format. As an example, the header will be added in this format: `-h "Content-Type: application/json"`. That said, when retrieving the individual key and value, I noticed that this was what I got: `["Content-Type: application/json"]`. Hence, I trimmed the brackets and quotations to obtain the key and value. Ideally, the headers should be processed before being stored but until then this will still work :D
