### PR TITLE
Update RunCommandParser and fix relevant error messages

### LINKED ISSUE #495: [PE-D] Requirements for URL parameter
The app specifies that the addresses should be in the form of an actual URL. However, for example, when i type "add -x GET -u test" it still adds the following endpoint and accepts the address. This could be slightly confusing for users and might be better to state the exact requirements of the values provided.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tashawan23/ped#4

### LINKED ISSUE #496: [PE-D] Error message does not match error
When i type "run 1" i get the error message: Connection was lost or could not be established. Check your internet connection and endpoint URL. This could also be a problem with the server you are attempting to connect to.
Maybe it would be clearer for users if the error message identified that the URL was not properly formatted or that the command format is incorrect instead.  

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tashawan23/ped#5

### LINKED ISSUE #514: [PE-D] Error message for run command not very useful
It does not check for invalid inputs and suggest a proper command format to the user.

￼

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: candyhy/ped#12

### PR DESCRIPTION
**Pull request by tlylt**
Fixes #495: added a note about URL validity in UG
Fixes #496, fixes #514: added more general error message

### CODE REVIEW

File: src/main/java/seedu/us/among/commons/core/Messages.java [hunk 1]
```diff
@@ -15,11 +15,18 @@
...
             + " that your data is added in the correct JSON format.";
-    public static final String MESSAGE_CONNECTION_ERROR = "Connection was lost or could not be established."
-            + " Check your internet connection and endpoint URL. This could also be a problem with the server"
-            + " you are attempting to connect to.";
+    public static final String MESSAGE_CONNECTION_ERROR = "Connection could not be established. Possible sources of "
+            + "error:\n"
+            + "- Invalid URL\n"
+            + "- Server error\n"
+            + "- Internet connection\n"
+            + "- Invalid command format\n";
```
Comment (ong6) [inline src/main/java/seedu/us/among/commons/core/Messages.java:23]: "Possible sources of error may include but are not limited to: "

might be a better way to put this

File: src/main/java/seedu/us/among/logic/parser/ParserUtil.java [hunk 2]
```diff
@@ -60,7 +60,7 @@ public static Method parseMethod(String method) throws ParseException {
     public static Address parseAddress(String address) throws ParseException {
         requireNonNull(address);
         String trimmedAddress = address.trim();
-
+        System.out.println("ADDRESS: " + address);
```
Comment (ong6) [inline src/main/java/seedu/us/among/logic/parser/ParserUtil.java:63]: Uhh, should this be here

File: src/main/java/seedu/us/among/logic/parser/RunCommandParser.java [hunk 3]
```diff
@@ -53,11 +55,13 @@ public RunCommand parse(String args) throws ParseException {
             throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, RunCommand.MESSAGE_USAGE));
         }
 
-        Method method = ParserUtil.parseMethod(argMultimap.getValue(PREFIX_METHOD).get());
-        Address address = ParserUtil.parseAddress(argMultimap.getValue(PREFIX_ADDRESS).get());
+        Method method = ParserUtil.parseMethod(argMultimap.getValue(PREFIX_METHOD).orElse(""));
+        Address address = ParserUtil.parseAddress(argMultimap.getValue(PREFIX_ADDRESS).orElse(""));
```
Comment (ong6) [inline src/main/java/seedu/us/among/logic/parser/RunCommandParser.java:59]: why is orElse used, i think a assert before this statement is more apt since there always should be a method and address, hence the method will never be empty

File: src/main/java/seedu/us/among/model/endpoint/Address.java [hunk 4]
```diff
@@ -16,7 +16,9 @@
 public class Address {
 
     public static final String MESSAGE_CONSTRAINTS =
-            "URL has to be a valid URL that does not contain any illegal characters. E.g. https://localhost:3000";
+            "URL provided has to be valid and does not contain any illegal characters.\nFor example:\n"
+                    + "https://localhost:3000\n"
+                    + "https://api.data.gov.sg/v1/environment/air-temperature";
```
Comment (ong6) [inline src/main/java/seedu/us/among/model/endpoint/Address.java:21]: maybe can add a OR between the 2 examples, or can put 1. 2. ...

**Review by ong6 — APPROVED** [review]
LGTM

File: src/main/java/seedu/us/among/logic/parser/ParserUtil.java (hunk 2 above)
Comment (tlylt) [reply src/main/java/seedu/us/among/logic/parser/ParserUtil.java:63]: will remove thx

File: src/main/java/seedu/us/among/logic/parser/RunCommandParser.java (hunk 3 above)
Comment (tlylt) [reply src/main/java/seedu/us/among/logic/parser/RunCommandParser.java:59]: given that it is never empty, using .get() or orElse() makes no difference, so I think it is better to avoid get

File: src/main/java/seedu/us/among/model/endpoint/Address.java (hunk 4 above)
Comment (tlylt) [reply src/main/java/seedu/us/among/model/endpoint/Address.java:21]: ok

File: src/main/java/seedu/us/among/commons/core/Messages.java (hunk 1 above)
Comment (tlylt) [reply src/main/java/seedu/us/among/commons/core/Messages.java:23]: ok
