### PR TITLE
Fix: add handling of exceptions when sending request

### LINKED ISSUE #187: Bug: a few exceptions are not caught when sending out requests
Currently, a generic exception message is thrown for all the following errors but is uninformative. Catch the following exceptions properly (and show formatted error messages) during a request:
- SocketTimeoutException (Involves connection loss or no response from server in the middle of request)
- JsonParseException (Involves using `'` instead of `"`)
- UnknownHostException (Involves connection loss before request is sent or unable to resolve hostname)
- ClientProtocolException (Involves invalid url)

@ong6 I'll catch the JsonParseException here but ideally a check should also be performed before storage. Doesn't hurt to check twice especially since users can directly edit the data file to bypass the check on `add` command.

### PR DESCRIPTION
**Pull request by tjtanjin**
In addressing the uncaught request exceptions, the following changes have been made:
- Add `RequestException` class to deal with 4 different exceptions thrown when sending a request.
- Timeout implemented for all requests, currently set to 1 minute.

Fixes #187

### CODE REVIEW

File: src/main/java/seedu/us/among/logic/endpoint/Request.java [hunk 1]
```diff
@@ -55,6 +56,20 @@ public String getAddress() {
      */
     public abstract Response send() throws IOException;
 
+    /**
+     * Creates a http client with timeout set to 60 seconds.
+     *
+     * @return http client to execute request
+     */
+    private CloseableHttpClient createHttpClient() {
+        int timeout = 60;
```
Comment (tlylt) [inline src/main/java/seedu/us/among/logic/endpoint/Request.java:65]: Perhaps timeout could be extracted out as a static constant to avoid magic number issues?

**Review by tlylt — APPROVED** [review]
Great job! Just one small note on `timeout`.

File: src/main/java/seedu/us/among/logic/endpoint/Request.java (hunk 1 above)
Comment (tjtanjin) [reply src/main/java/seedu/us/among/logic/endpoint/Request.java]: Great suggestion, changed this in the latest commit! :)
